-- =====================================================================
-- Academic Research Metadata Repository : 01_schema.sql
-- PostgreSQL 14+ (tested on 16).  Run order: 01 -> 02 -> 03/04/05
-- Re-runnable: drops and recreates everything.
-- =====================================================================

DROP TABLE    IF EXISTS citation, paper_subject, paper_author,
                        paper, subject, author, journal, publisher CASCADE;
DROP FUNCTION IF EXISTS check_paper_has_author()         CASCADE;
DROP FUNCTION IF EXISTS check_citation_years()           CASCADE;
DROP FUNCTION IF EXISTS check_paper_year_vs_citations()  CASCADE;

CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- trigram fuzzy matching

-- ---------------------------------------------------------------------
-- 1. PUBLISHER   (1 publisher : N journals)
-- ---------------------------------------------------------------------
CREATE TABLE publisher (
    publisher_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(200) NOT NULL,
    CONSTRAINT pk_publisher      PRIMARY KEY (publisher_id),
    CONSTRAINT uq_publisher_name UNIQUE (name)
);

-- ---------------------------------------------------------------------
-- 2. JOURNAL     (every journal has exactly one publisher)
-- ---------------------------------------------------------------------
CREATE TABLE journal (
    journal_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name         VARCHAR(300) NOT NULL,
    issn         VARCHAR(9),                       -- nullable: not every journal has one
    publisher_id INTEGER      NOT NULL,            -- NOT NULL => "exactly one"
    CONSTRAINT pk_journal        PRIMARY KEY (journal_id),
    CONSTRAINT uq_journal_issn   UNIQUE (issn),    -- ISSN identifies a journal
    CONSTRAINT ck_journal_issn   CHECK (issn ~ '^[0-9]{4}-[0-9]{3}[0-9X]$'),
    CONSTRAINT fk_journal_publisher
        FOREIGN KEY (publisher_id) REFERENCES publisher (publisher_id)
        ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------
-- 3. AUTHOR
-- ---------------------------------------------------------------------
CREATE TABLE author (
    author_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(200) NOT NULL,             -- NOT unique: different people share names
    affiliation VARCHAR(300),
    CONSTRAINT pk_author PRIMARY KEY (author_id)
);

-- ---------------------------------------------------------------------
-- 4. SUBJECT
-- ---------------------------------------------------------------------
CREATE TABLE subject (
    subject_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_subject      PRIMARY KEY (subject_id),
    CONSTRAINT uq_subject_name UNIQUE (name)
);

-- ---------------------------------------------------------------------
-- 5. PAPER       (every paper is in exactly one journal)
-- ---------------------------------------------------------------------
CREATE TABLE paper (
    paper_id   INTEGER GENERATED BY DEFAULT AS IDENTITY,
    title      TEXT      NOT NULL,
    pub_year   SMALLINT  NOT NULL,
    doi        VARCHAR(255),                       -- nullable, but unique when present
    abstract   TEXT,
    journal_id INTEGER   NOT NULL,                 -- NOT NULL => "exactly one"
    CONSTRAINT pk_paper      PRIMARY KEY (paper_id),
    CONSTRAINT uq_paper_doi  UNIQUE (doi),
    CONSTRAINT ck_paper_year CHECK (pub_year BETWEEN 1900 AND 2100),
    CONSTRAINT ck_paper_doi  CHECK (doi ~ '^10\.[0-9]{4,9}/\S+$'),
    CONSTRAINT fk_paper_journal
        FOREIGN KEY (journal_id) REFERENCES journal (journal_id)
        ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------
-- 6. PAPER_AUTHOR   (M:N  paper <-> author, with author position)
-- ---------------------------------------------------------------------
CREATE TABLE paper_author (
    paper_id     INTEGER  NOT NULL,
    author_id    INTEGER  NOT NULL,
    author_order SMALLINT NOT NULL,
    CONSTRAINT pk_paper_author PRIMARY KEY (paper_id, author_id),
    CONSTRAINT uq_paper_author_order UNIQUE (paper_id, author_order),  -- 2nd candidate key
    CONSTRAINT ck_author_order CHECK (author_order >= 1),
    CONSTRAINT fk_pa_paper  FOREIGN KEY (paper_id)  REFERENCES paper  (paper_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_pa_author FOREIGN KEY (author_id) REFERENCES author (author_id)
        ON DELETE RESTRICT
);

-- ---------------------------------------------------------------------
-- 7. PAPER_SUBJECT  (M:N  paper <-> subject, optional on both sides)
-- ---------------------------------------------------------------------
CREATE TABLE paper_subject (
    paper_id   INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    CONSTRAINT pk_paper_subject PRIMARY KEY (paper_id, subject_id),
    CONSTRAINT fk_ps_paper   FOREIGN KEY (paper_id)   REFERENCES paper   (paper_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_ps_subject FOREIGN KEY (subject_id) REFERENCES subject (subject_id)
        ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- 8. CITATION   (self-referencing M:N on PAPER)
-- ---------------------------------------------------------------------
CREATE TABLE citation (
    citing_paper_id INTEGER NOT NULL,
    cited_paper_id  INTEGER NOT NULL,
    CONSTRAINT pk_citation PRIMARY KEY (citing_paper_id, cited_paper_id),
    CONSTRAINT ck_no_self_citation CHECK (citing_paper_id <> cited_paper_id),
    CONSTRAINT fk_cit_citing FOREIGN KEY (citing_paper_id) REFERENCES paper (paper_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_cit_cited  FOREIGN KEY (cited_paper_id)  REFERENCES paper (paper_id)
        ON DELETE CASCADE
);

-- =====================================================================
-- BUSINESS RULES THAT PLAIN CONSTRAINTS CANNOT EXPRESS  (triggers)
-- =====================================================================

-- Rule A: every paper has at least one author.
-- DEFERRED, so a paper and its author rows can be inserted in the same
-- transaction; the check runs at COMMIT.
CREATE FUNCTION check_paper_has_author() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    pid INTEGER;
BEGIN
    IF TG_TABLE_NAME = 'paper' THEN pid := NEW.paper_id;
    ELSE                            pid := OLD.paper_id;
    END IF;
    -- if the paper itself is gone (cascade delete), nothing to enforce
    IF EXISTS (SELECT 1 FROM paper WHERE paper_id = pid)
       AND NOT EXISTS (SELECT 1 FROM paper_author WHERE paper_id = pid) THEN
        RAISE EXCEPTION 'paper % must have at least one author', pid
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END $$;

CREATE CONSTRAINT TRIGGER trg_paper_needs_author
    AFTER INSERT ON paper
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION check_paper_has_author();

CREATE CONSTRAINT TRIGGER trg_paper_author_keeps_one
    AFTER DELETE OR UPDATE OF paper_id ON paper_author
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION check_paper_has_author();

-- Rule B: a paper may only cite papers from an EARLIER year.
-- (Also makes the citation graph acyclic by construction.)
CREATE FUNCTION check_citation_years() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    citing_year SMALLINT;
    cited_year  SMALLINT;
BEGIN
    SELECT pub_year INTO citing_year FROM paper WHERE paper_id = NEW.citing_paper_id;
    SELECT pub_year INTO cited_year  FROM paper WHERE paper_id = NEW.cited_paper_id;
    IF cited_year >= citing_year THEN
        RAISE EXCEPTION 'paper % (%) cannot cite paper % (%): cited paper must be from an earlier year',
            NEW.citing_paper_id, citing_year, NEW.cited_paper_id, cited_year
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END $$;

CREATE TRIGGER trg_citation_years
    BEFORE INSERT OR UPDATE ON citation
    FOR EACH ROW EXECUTE FUNCTION check_citation_years();

-- Rule B (continued): changing a paper's year must not break existing citations.
CREATE FUNCTION check_paper_year_vs_citations() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM citation c
        JOIN paper a ON a.paper_id = c.citing_paper_id
        JOIN paper b ON b.paper_id = c.cited_paper_id
        WHERE (c.citing_paper_id = NEW.paper_id OR c.cited_paper_id = NEW.paper_id)
          AND b.pub_year >= a.pub_year
    ) THEN
        RAISE EXCEPTION 'changing pub_year of paper % would break the "cites earlier papers" rule',
            NEW.paper_id USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END $$;

CREATE TRIGGER trg_paper_year_update
    AFTER UPDATE OF pub_year ON paper
    FOR EACH ROW EXECUTE FUNCTION check_paper_year_vs_citations();

-- =====================================================================
-- INDEXES
-- PK / UNIQUE constraints already create their own indexes.
-- The ones below serve foreign keys that are NOT the leading column of a
-- PK/UNIQUE index, plus the trigram index for fuzzy title search.
-- =====================================================================
CREATE INDEX idx_journal_publisher ON journal (publisher_id);
CREATE INDEX idx_paper_journal     ON paper (journal_id);
CREATE INDEX idx_pa_author         ON paper_author (author_id);    -- papers BY author
CREATE INDEX idx_ps_subject        ON paper_subject (subject_id);  -- papers IN subject
CREATE INDEX idx_cit_cited         ON citation (cited_paper_id);   -- "cited by"
CREATE INDEX idx_paper_title_trgm  ON paper USING GIN (title gin_trgm_ops);
